CREATE TABLE STAGING.DEBUG_TMP_DAILY_DATA
(
    LOAD_ID                 integer,
    RETAILER                RETAILERS,
    EAN                     text,
    DATE                    date,
    HREF                    text,
    SIZE                    text,
    "eposId"                text,
    STATUS                  text,
    BUNDLED                 boolean,
    CATEGORY                text,
    FEATURED                boolean,
    FEATURES                text,
    PROMOTIONS              STAGING.T_PROMOTION[],
    MULTIBUY                boolean,
    "sizeUnit"              text,
    "sourceId"              text,
    "inTaxonomy"            boolean,
    "isFeatured"            boolean,
    "pageNumber"            text,
    SCREENSHOT              text,
    "sourceType"            text,
    "taxonomyId"            integer,
    NUTRITIONAL             text,
    "productInfo"           text,
    "productRank"           integer,
    "categoryType"          text,
    "featuredRank"          integer,
    "productBrand"          text,
    "productImage"          text,
    "newCoreImage"          text,
    "productPrice"          double precision,
    "productTitle"          text,
    "reviewsCount"          integer,
    "reviewsStars"          double precision,
    "originalPrice"         double precision,
    "pricePerWeight"        text,
    "productInStock"        boolean,
    "secondaryImages"       boolean,
    "productDescription"    text,
    "productTitleDetail"    text,
    "promotionDescription"  text,
    "productOptions"        boolean,
    SHOP                    text,
    "amazonShop"            text,
    CHOICE                  text,
    "amazonChoice"          text,
    "lowStock"              boolean,
    "sellParty"             text,
    "amazonSellParty"       text,
    SELL                    text,
    "fulfilParty"           text,
    "amazonFulfilParty"     text,
    "amazonSell"            text,
    MARKETPLACE             boolean,
    "marketplaceData"       JSON,
    "priceMatchDescription" text,
    "priceMatch"            boolean,
    "priceLock"             boolean,
    "isNpd"                 boolean
);

ALTER TABLE STAGING.DEBUG_TMP_DAILY_DATA
    OWNER TO POSTGRES;

GRANT SELECT ON STAGING.DEBUG_TMP_DAILY_DATA TO BN_RO;

GRANT SELECT ON STAGING.DEBUG_TMP_DAILY_DATA TO DEJAN_USER;

