CREATE TABLE STAGING.DEBUG_TMP_PRODUCT_PP_REMOVED
(
    LOAD_ID                 integer,
    ID                      integer,
    "sourceType"            varchar(255),
    EAN                     text,
    "promotionDescription"  text,
    FEATURES                text,
    DATE                    date,
    "sourceId"              text,
    "productBrand"          text,
    "productTitle"          text,
    "productImage"          text,
    "newCoreImage"          text,
    "secondaryImages"       boolean,
    "productDescription"    text,
    "productInfo"           text,
    "promotedPrice"         double precision,
    "productInStock"        boolean,
    "productInListing"      boolean,
    "reviewsCount"          integer,
    "reviewsStars"          double precision,
    "eposId"                text,
    MULTIBUY                boolean,
    "coreProductId"         integer,
    "retailerId"            integer,
    "createdAt"             timestamp with time zone,
    "updatedAt"             timestamp with time zone,
    "imageId"               text,
    SIZE                    text,
    "pricePerWeight"        text,
    HREF                    text,
    NUTRITIONAL             text,
    "basePrice"             double precision,
    "shelfPrice"            double precision,
    "productTitleDetail"    text,
    "sizeUnit"              text,
    "dateId"                integer,
    "countryCode"           text,
    CURRENCY                text,
    "cardPrice"             double precision,
    "onPromo"               boolean,
    BUNDLED                 boolean,
    "originalPrice"         double precision,
    "productPrice"          double precision,
    STATUS                  text,
    "productOptions"        boolean,
    SHOP                    text,
    "amazonShop"            text,
    CHOICE                  text,
    "amazonChoice"          text,
    "lowStock"              boolean,
    "sellParty"             text,
    "amazonSellParty"       text,
    SELL                    text,
    "fulfilParty"           text,
    "amazonFulfilParty"     text,
    "amazonSell"            text,
    MARKETPLACE             boolean,
    "marketplaceData"       JSON,
    "priceMatchDescription" text,
    "priceMatch"            boolean,
    "priceLock"             boolean,
    "isNpd"                 boolean,
    "eanIssues"             boolean,
    SCREENSHOT              text,
    "brandId"               integer,
    "EANs"                  text[],
    PROMOTIONS              STAGING.T_PROMOTION_MB[]
);

ALTER TABLE STAGING.DEBUG_TMP_PRODUCT_PP_REMOVED
    OWNER TO POSTGRES;

GRANT SELECT ON STAGING.DEBUG_TMP_PRODUCT_PP_REMOVED TO BN_RO;

GRANT SELECT ON STAGING.DEBUG_TMP_PRODUCT_PP_REMOVED TO DEJAN_USER;

