CREATE TABLE STAGING.PRODUCT_STATUS_HISTORY
(
    "retailerId"    integer NOT NULL,
    "coreProductId" integer NOT NULL,
    DATE            date    NOT NULL,
    "productId"     integer
        CONSTRAINT PRODUCT_STATUS_HISTORY_PRODUCTID_UINDEX
            UNIQUE,
    STATUS          text,
    CONSTRAINT PRODUCT_STATUS_HISTORY_PK
        PRIMARY KEY ("retailerId", "coreProductId", DATE)
);

ALTER TABLE STAGING.PRODUCT_STATUS_HISTORY
    OWNER TO POSTGRES;

GRANT SELECT ON STAGING.PRODUCT_STATUS_HISTORY TO BN_RO;

GRANT SELECT ON STAGING.PRODUCT_STATUS_HISTORY TO DEJAN_USER;

