CREATE TYPE STAGING.RETAILER_DATA AS
(
    RETAILER                RETAILERS,
    EAN                     text,
    DATE                    date,
    HREF                    text,
    SIZE                    text,
    "eposId"                text,
    STATUS                  text,
    BUNDLED                 boolean,
    CATEGORY                text,
    FEATURED                boolean,
    FEATURES                text,
    PROMOTIONS              STAGING.T_PROMOTION[],
    MULTIBUY                boolean,
    "sizeUnit"              text,
    "sourceId"              text,
    "inTaxonomy"            boolean,
    "isFeatured"            boolean,
    "pageNumber"            text,
    SCREENSHOT              text,
    "sourceType"            text,
    "taxonomyId"            integer,
    NUTRITIONAL             text,
    "productInfo"           text,
    "productRank"           integer,
    "categoryType"          text,
    "featuredRank"          integer,
    "productBrand"          text,
    "productImage"          text,
    "newCoreImage"          text,
    "productPrice"          text,
    "productTitle"          text,
    "reviewsCount"          integer,
    "reviewsStars"          text,
    "originalPrice"         text,
    "pricePerWeight"        text,
    "productInStock"        boolean,
    "secondaryImages"       boolean,
    "productDescription"    text,
    "productTitleDetail"    text,
    "promotionDescription"  text,
    "productOptions"        boolean,
    SHOP                    text,
    "amazonShop"            text,
    CHOICE                  text,
    "amazonChoice"          text,
    "lowStock"              boolean,
    "sellParty"             text,
    "amazonSellParty"       text,
    SELL                    text,
    "fulfilParty"           text,
    "amazonFulfilParty"     text,
    "amazonSell"            text,
    MARKETPLACE             boolean,
    "marketplaceData"       JSON,
    "priceMatchDescription" text,
    "priceMatch"            boolean,
    "priceLock"             boolean,
    "isNpd"                 boolean
);

ALTER TYPE STAGING.RETAILER_DATA OWNER TO POSTGRES;

