CREATE TYPE STAGING.RETAILER_DATA_PP AS
(
    DATE                    date,
    RETAILER                text,
    "countryCode"           text,
    CURRENCY                text,
    "sourceId"              text,
    EAN                     text,
    BRAND                   text,
    TITLE                   text,
    "shelfPrice"            text,
    "wasPrice"              text,
    "cardPrice"             text,
    "inStock"               text,
    "onPromo"               text,
    "promoData"             STAGING.T_PROMOTION_PP[],
    "skuURL"                text,
    "imageURL"              text,
    "newCoreImage"          text,
    BUNDLED                 text,
    "masterSku"             text,
    SHOP                    text,
    "amazonShop"            text,
    CHOICE                  text,
    "amazonChoice"          text,
    "lowStock"              boolean,
    "sellParty"             text,
    "amazonSellParty"       text,
    SELL                    text,
    "fulfilParty"           text,
    "amazonFulfilParty"     text,
    "amazonSell"            text,
    MARKETPLACE             boolean,
    "marketplaceData"       JSON,
    "priceMatchDescription" text,
    "priceMatch"            boolean,
    "priceLock"             boolean,
    "isNpd"                 boolean,
    SIZE                    text,
    "sizeUnit"              text,
    "pricePerWeight"        text,
    "reviewsCount"          text,
    "reviewsStars"          text
);

ALTER TYPE STAGING.RETAILER_DATA_PP OWNER TO POSTGRES;

