CREATE TABLE STAGING.RETAILER_DAILY_DATA
(
    LOAD_ID      serial,
    FETCHED_DATA JSON,
    FLAG         text,
    CREATED_AT   timestamp with time zone DEFAULT NOW()
);

ALTER TABLE STAGING.RETAILER_DAILY_DATA
    OWNER TO POSTGRES;

GRANT SELECT ON STAGING.RETAILER_DAILY_DATA TO BN_RO;

GRANT SELECT ON STAGING.RETAILER_DAILY_DATA TO DEJAN_USER;

