CREATE TYPE STAGING.T_PROMOTION_PP AS
(
    PROMO_ID          text,
    PROMO_TYPE        text,
    PROMO_DESCRIPTION text,
    MULTIBUY_PRICE    text
);

ALTER TYPE STAGING.T_PROMOTION_PP OWNER TO POSTGRES;

