CREATE SEQUENCE CATEGORIES_ID_SEQ;

ALTER SEQUENCE CATEGORIES_ID_SEQ OWNER TO POSTGRES;

ALTER SEQUENCE CATEGORIES_ID_SEQ OWNED BY CATEGORIES.ID;

GRANT SELECT ON SEQUENCE CATEGORIES_ID_SEQ TO DEJAN_USER;

