CREATE SEQUENCE COMPANIES_ID_SEQ;

ALTER SEQUENCE COMPANIES_ID_SEQ OWNER TO POSTGRES;

ALTER SEQUENCE COMPANIES_ID_SEQ OWNED BY COMPANIES.ID;

GRANT SELECT ON SEQUENCE COMPANIES_ID_SEQ TO DEJAN_USER;

