CREATE SEQUENCE CORETAGGINGS_ID_SEQ;

ALTER SEQUENCE CORETAGGINGS_ID_SEQ OWNER TO POSTGRES;

ALTER SEQUENCE CORETAGGINGS_ID_SEQ OWNED BY "coreTaggings".ID;

GRANT SELECT ON SEQUENCE CORETAGGINGS_ID_SEQ TO DEJAN_USER;

