CREATE SEQUENCE MANUFACTURERS_ID_SEQ;

ALTER SEQUENCE MANUFACTURERS_ID_SEQ OWNER TO POSTGRES;

ALTER SEQUENCE MANUFACTURERS_ID_SEQ OWNED BY MANUFACTURERS.ID;

GRANT SELECT ON SEQUENCE MANUFACTURERS_ID_SEQ TO DEJAN_USER;

