CREATE FUNCTION POSTGRES_FDW_VALIDATOR(text[], oid) RETURNS void
    STRICT
    LANGUAGE C
AS
$$
begin
-- missing source code
end;
$$;

ALTER FUNCTION POSTGRES_FDW_VALIDATOR(text[], oid) OWNER TO RDS_SUPERUSER;

