CREATE SEQUENCE RETAILERS_ID_SEQ;

ALTER SEQUENCE RETAILERS_ID_SEQ OWNER TO POSTGRES;

ALTER SEQUENCE RETAILERS_ID_SEQ OWNED BY RETAILERS.ID;

GRANT SELECT ON SEQUENCE RETAILERS_ID_SEQ TO DEJAN_USER;

