CREATE SEQUENCE TAXONOMIES_ID_SEQ;

ALTER SEQUENCE TAXONOMIES_ID_SEQ OWNER TO POSTGRES;

ALTER SEQUENCE TAXONOMIES_ID_SEQ OWNED BY TAXONOMIES.ID;

GRANT SELECT ON SEQUENCE TAXONOMIES_ID_SEQ TO DEJAN_USER;

