CREATE TABLE DATA_CORR.FIX_TITLE_MATCH_PRODUCTS
(
    "productId"     integer,
    "coreProductId" integer,
    "countryId"     integer,
    "productTitle"  text
);

ALTER TABLE DATA_CORR.FIX_TITLE_MATCH_PRODUCTS
    OWNER TO POSTGRES;

CREATE INDEX FIX_TITLE_MATCH_PRODUCTS_COUNTRYID_COREPRODUCTID_INDEX
    ON DATA_CORR.FIX_TITLE_MATCH_PRODUCTS ("countryId", "coreProductId");

GRANT SELECT ON DATA_CORR.FIX_TITLE_MATCH_PRODUCTS TO BN_RO;

GRANT SELECT ON DATA_CORR.FIX_TITLE_MATCH_PRODUCTS TO DEJAN_USER;

