CREATE TABLE DATA_CORR.FIX_PRODUCT_STATUS_HISTORY_BCK
(
    "retailerId"    integer,
    "coreProductId" integer,
    DATE            date,
    "productId"     integer,
    STATUS          text
);

ALTER TABLE DATA_CORR.FIX_PRODUCT_STATUS_HISTORY_BCK
    OWNER TO POSTGRES;

GRANT SELECT ON DATA_CORR.FIX_PRODUCT_STATUS_HISTORY_BCK TO BN_RO;

GRANT SELECT ON DATA_CORR.FIX_PRODUCT_STATUS_HISTORY_BCK TO DEJAN_USER;

