CREATE TABLE DATA_CORR.FIX_PRODUCT_STATUS_HISTORY_COREPRODUCTS
(
    "productId"          integer,
    DATE                 timestamp with time zone,
    "dateId"             integer,
    LOAD_ID              integer,
    LATEST_COREPRODUCTID integer
);

ALTER TABLE DATA_CORR.FIX_PRODUCT_STATUS_HISTORY_COREPRODUCTS
    OWNER TO POSTGRES;

GRANT SELECT ON DATA_CORR.FIX_PRODUCT_STATUS_HISTORY_COREPRODUCTS TO BN_RO;

GRANT SELECT ON DATA_CORR.FIX_PRODUCT_STATUS_HISTORY_COREPRODUCTS TO DEJAN_USER;

