CREATE TABLE DATA_CORR.FIX_TITLE_MATCH_PRODUCTS_UPDATED
(
    "productId"  integer,
    "titleMatch" text
);

ALTER TABLE DATA_CORR.FIX_TITLE_MATCH_PRODUCTS_UPDATED
    OWNER TO POSTGRES;

CREATE INDEX FIX_TITLE_MATCH_PRODUCTS_UPDATED_PRODUCTID_INDEX
    ON DATA_CORR.FIX_TITLE_MATCH_PRODUCTS_UPDATED ("productId");

GRANT SELECT ON DATA_CORR.FIX_TITLE_MATCH_PRODUCTS_UPDATED TO BN_RO;

GRANT SELECT ON DATA_CORR.FIX_TITLE_MATCH_PRODUCTS_UPDATED TO DEJAN_USER;

