CREATE TABLE DATA_CORR.MS2_DATA_CORR_STATUS_EXTRA_DELISTED_DELETED
(
    ID          integer,
    "productId" integer,
    STATUS      varchar(255),
    SCREENSHOT  varchar(255),
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    LOAD_ID     integer
);

ALTER TABLE DATA_CORR.MS2_DATA_CORR_STATUS_EXTRA_DELISTED_DELETED
    OWNER TO POSTGRES;

GRANT SELECT ON DATA_CORR.MS2_DATA_CORR_STATUS_EXTRA_DELISTED_DELETED TO BN_RO;

GRANT SELECT ON DATA_CORR.MS2_DATA_CORR_STATUS_EXTRA_DELISTED_DELETED TO DEJAN_USER;

