CREATE TABLE DATA_CORR.PRODUCTS_1_29980_BCK
(
    ID                      integer,
    "sourceType"            varchar(255),
    EAN                     varchar(255),
    PROMOTIONS              boolean,
    "promotionDescription"  text,
    FEATURES                text,
    DATE                    timestamp with time zone,
    "sourceId"              varchar(255),
    "productBrand"          varchar(255),
    "productTitle"          text,
    "productImage"          text,
    "secondaryImages"       boolean,
    "productDescription"    text,
    "productInfo"           text,
    "promotedPrice"         varchar(255),
    "productInStock"        boolean,
    "productInListing"      boolean,
    "reviewsCount"          varchar(255),
    "reviewsStars"          varchar(255),
    "eposId"                varchar(255),
    MULTIBUY                boolean,
    "coreProductId"         integer,
    "retailerId"            integer,
    "createdAt"             timestamp with time zone,
    "updatedAt"             timestamp with time zone,
    "imageId"               integer,
    SIZE                    varchar(255),
    "pricePerWeight"        varchar(255),
    HREF                    text,
    NUTRITIONAL             text,
    "basePrice"             varchar(255),
    "shelfPrice"            varchar(255),
    "productTitleDetail"    text,
    "sizeUnit"              varchar(255),
    "dateId"                integer,
    MARKETPLACE             boolean,
    "marketplaceData"       JSON,
    "priceMatchDescription" text,
    "priceMatch"            boolean,
    "priceLock"             boolean,
    "isNpd"                 boolean,
    LOAD_ID                 integer,
    "productsDataId"        integer,
    "productId"             integer,
    CATEGORY                varchar(255),
    "categoryType"          varchar(255),
    "parentCategory"        varchar(255),
    "productRank"           integer,
    "pageNumber"            varchar(255),
    SCREENSHOT              varchar(255),
    FEATURED                boolean,
    "featuredRank"          integer,
    "taxonomyId"            integer,
    "productsDataload_id"   integer
);

ALTER TABLE DATA_CORR.PRODUCTS_1_29980_BCK
    OWNER TO POSTGRES;

GRANT SELECT ON DATA_CORR.PRODUCTS_1_29980_BCK TO BN_RO;

GRANT SELECT ON DATA_CORR.PRODUCTS_1_29980_BCK TO DEJAN_USER;

