CREATE TABLE MIGRATION.MIGRET_INS_PRODUCTSTATUSES2
(
    "productId" integer,
    STATUS      text
);

ALTER TABLE MIGRATION.MIGRET_INS_PRODUCTSTATUSES2
    OWNER TO POSTGRES;

GRANT SELECT ON MIGRATION.MIGRET_INS_PRODUCTSTATUSES2 TO BN_RO;

GRANT SELECT ON MIGRATION.MIGRET_INS_PRODUCTSTATUSES2 TO DEJAN_USER;

