CREATE TABLE MIGRATION.MS2_MIGSTATUS_PRODUCTS_FILTERED
(
    "retailerId"    integer,
    "coreProductId" integer,
    LOAD_DATE       date,
    "productId"     integer
);

ALTER TABLE MIGRATION.MS2_MIGSTATUS_PRODUCTS_FILTERED
    OWNER TO POSTGRES;

CREATE INDEX MS2_MIGSTATUS_PRODUCTS_FILTERED_RETAILERID_COREPRODUCTID_DATE_I
    ON MIGRATION.MS2_MIGSTATUS_PRODUCTS_FILTERED ("retailerId", "coreProductId", LOAD_DATE);

GRANT SELECT ON MIGRATION.MS2_MIGSTATUS_PRODUCTS_FILTERED TO BN_RO;

GRANT SELECT ON MIGRATION.MS2_MIGSTATUS_PRODUCTS_FILTERED TO DEJAN_USER;

