CREATE TABLE MIGRATION.MS2_MIGRATION_MIGRATED_RETAILERS
(
    "retailerId"    integer NOT NULL
        PRIMARY KEY,
    MIGRATION_START timestamp DEFAULT NOW(),
    MIGRATION_END   timestamp
);

ALTER TABLE MIGRATION.MS2_MIGRATION_MIGRATED_RETAILERS
    OWNER TO POSTGRES;

GRANT SELECT ON MIGRATION.MS2_MIGRATION_MIGRATED_RETAILERS TO BN_RO;

GRANT SELECT ON MIGRATION.MS2_MIGRATION_MIGRATED_RETAILERS TO DEJAN_USER;

