CREATE TABLE MIGRATION.MS2_MIGSTATUS_LAST_LOAD_PRODUCT
(
    "retailerId"    integer,
    "coreProductId" integer,
    DELISTED_DATE   date,
    LOAD_DATE       date
);

ALTER TABLE MIGRATION.MS2_MIGSTATUS_LAST_LOAD_PRODUCT
    OWNER TO POSTGRES;

GRANT SELECT ON MIGRATION.MS2_MIGSTATUS_LAST_LOAD_PRODUCT TO BN_RO;

GRANT SELECT ON MIGRATION.MS2_MIGSTATUS_LAST_LOAD_PRODUCT TO DEJAN_USER;

