CREATE TABLE MIGRATION.MS2_TMP_MIG2ND_FIX_DUP_STATUS
(
    "retailerId"    integer,
    "coreProductId" integer,
    DATE            date,
    "productId"     integer,
    STATUS          text
);

ALTER TABLE MIGRATION.MS2_TMP_MIG2ND_FIX_DUP_STATUS
    OWNER TO POSTGRES;

GRANT SELECT ON MIGRATION.MS2_TMP_MIG2ND_FIX_DUP_STATUS TO BN_RO;

GRANT SELECT ON MIGRATION.MS2_TMP_MIG2ND_FIX_DUP_STATUS TO DEJAN_USER;

