CREATE TABLE MIGRATION.MS2_TMP_MIG2ND_PRODUCT_STATUS_HISTORY
(
    "retailerId"    integer,
    "coreProductId" integer,
    DATE            date,
    "productId"     integer,
    STATUS          text
);

ALTER TABLE MIGRATION.MS2_TMP_MIG2ND_PRODUCT_STATUS_HISTORY
    OWNER TO POSTGRES;

CREATE INDEX TMP_PRODUCT_STATUS_HISTORY_PRODUCTID_UINDEX
    ON MIGRATION.MS2_TMP_MIG2ND_PRODUCT_STATUS_HISTORY ("productId");

GRANT SELECT ON MIGRATION.MS2_TMP_MIG2ND_PRODUCT_STATUS_HISTORY TO BN_RO;

GRANT SELECT ON MIGRATION.MS2_TMP_MIG2ND_PRODUCT_STATUS_HISTORY TO DEJAN_USER;

