CREATE TABLE MIGRATION.MS2_TMP_MIG2ND_DUP_PROD_STAT_HISTORY
(
    "retailerId"    integer,
    "coreProductId" integer,
    DATE            date,
    "productId"     integer,
    STATUS          text
);

ALTER TABLE MIGRATION.MS2_TMP_MIG2ND_DUP_PROD_STAT_HISTORY
    OWNER TO POSTGRES;

GRANT SELECT ON MIGRATION.MS2_TMP_MIG2ND_DUP_PROD_STAT_HISTORY TO BN_RO;

GRANT SELECT ON MIGRATION.MS2_TMP_MIG2ND_DUP_PROD_STAT_HISTORY TO DEJAN_USER;

