CREATE TABLE MIGRATION.MS2_MIGSTATUS_DELISTED
(
    "retailerId"    integer NOT NULL,
    "coreProductId" integer NOT NULL,
    DELISTED_DATE   date    NOT NULL,
    CONSTRAINT MIGSTATUS_DELISTED_PK
        PRIMARY KEY (DELISTED_DATE, "coreProductId", "retailerId")
);

ALTER TABLE MIGRATION.MS2_MIGSTATUS_DELISTED
    OWNER TO POSTGRES;

GRANT SELECT ON MIGRATION.MS2_MIGSTATUS_DELISTED TO BN_RO;

GRANT SELECT ON MIGRATION.MS2_MIGSTATUS_DELISTED TO DEJAN_USER;

