CREATE TABLE MIGRATION.MS2_MIGSTATUS_INS_PROD_SELECTION
(
    ID               integer NOT NULL
        CONSTRAINT MIGSTATUS_INS_PROD_SELECTION_PK
            PRIMARY KEY,
    DELISTED_DATE    date,
    DELISTED_DATE_ID integer
);

ALTER TABLE MIGRATION.MS2_MIGSTATUS_INS_PROD_SELECTION
    OWNER TO POSTGRES;

GRANT SELECT ON MIGRATION.MS2_MIGSTATUS_INS_PROD_SELECTION TO BN_RO;

GRANT SELECT ON MIGRATION.MS2_MIGSTATUS_INS_PROD_SELECTION TO DEJAN_USER;

