CREATE TABLE MIGRATION.MS2_MIG_PROD_STAT_MULTIPLE_IN_SAME_DAY
(
    ID          integer,
    "productId" integer,
    STATUS      varchar(255),
    SCREENSHOT  varchar(255),
    "createdAt" timestamp with time zone,
    "updatedAt" timestamp with time zone,
    LOAD_ID     integer
);

ALTER TABLE MIGRATION.MS2_MIG_PROD_STAT_MULTIPLE_IN_SAME_DAY
    OWNER TO POSTGRES;

GRANT SELECT ON MIGRATION.MS2_MIG_PROD_STAT_MULTIPLE_IN_SAME_DAY TO BN_RO;

GRANT SELECT ON MIGRATION.MS2_MIG_PROD_STAT_MULTIPLE_IN_SAME_DAY TO DEJAN_USER;

