CREATE FOREIGN TABLE PRODDB_STAGING_FDW.DEBUG_TMP_PRODUCT
    (
        LOAD_ID integer OPTIONS (column_name 'load_id'),
        ID integer OPTIONS (column_name 'id'),
        "coreProductId" integer OPTIONS (column_name 'coreProductId'),
        PROMOTIONS STAGING.T_PROMOTION[] OPTIONS (column_name 'promotions'),
        "productPrice" double precision OPTIONS (column_name 'productPrice'),
        "originalPrice" double precision OPTIONS (column_name 'originalPrice'),
        "basePrice" double precision OPTIONS (column_name 'basePrice'),
        "shelfPrice" double precision OPTIONS (column_name 'shelfPrice'),
        "promotedPrice" double precision OPTIONS (column_name 'promotedPrice'),
        "retailerId" integer OPTIONS (column_name 'retailerId'),
        "dateId" integer OPTIONS (column_name 'dateId'),
        FEATURED boolean OPTIONS (column_name 'featured'),
        BUNDLED boolean OPTIONS (column_name 'bundled'),
        DATE date OPTIONS (column_name 'date'),
        EAN text OPTIONS (column_name 'ean'),
        "eposId" text OPTIONS (column_name 'eposId'),
        FEATURES text OPTIONS (column_name 'features'),
        HREF text OPTIONS (column_name 'href'),
        "inTaxonomy" boolean OPTIONS (column_name 'inTaxonomy'),
        "isFeatured" boolean OPTIONS (column_name 'isFeatured'),
        MULTIBUY boolean OPTIONS (column_name 'multibuy'),
        NUTRITIONAL text OPTIONS (column_name 'nutritional'),
        "pricePerWeight" text OPTIONS (column_name 'pricePerWeight'),
        "productBrand" text OPTIONS (column_name 'productBrand'),
        "productDescription" text OPTIONS (column_name 'productDescription'),
        "productImage" text OPTIONS (column_name 'productImage'),
        "newCoreImage" text OPTIONS (column_name 'newCoreImage'),
        "productInStock" boolean OPTIONS (column_name 'productInStock'),
        "productInfo" text OPTIONS (column_name 'productInfo'),
        "productTitle" text OPTIONS (column_name 'productTitle'),
        "productTitleDetail" text OPTIONS (column_name 'productTitleDetail'),
        "reviewsCount" integer OPTIONS (column_name 'reviewsCount'),
        "reviewsStars" double precision OPTIONS (column_name 'reviewsStars'),
        "secondaryImages" boolean OPTIONS (column_name 'secondaryImages'),
        SIZE text OPTIONS (column_name 'size'),
        "sizeUnit" text OPTIONS (column_name 'sizeUnit'),
        "sourceId" text OPTIONS (column_name 'sourceId'),
        "sourceType" text OPTIONS (column_name 'sourceType'),
        "brandId" integer OPTIONS (column_name 'brandId'),
        "productOptions" boolean OPTIONS (column_name 'productOptions'),
        "eanIssues" boolean OPTIONS (column_name 'eanIssues'),
        SHOP text OPTIONS (column_name 'shop'),
        "amazonShop" text OPTIONS (column_name 'amazonShop'),
        CHOICE text OPTIONS (column_name 'choice'),
        "amazonChoice" text OPTIONS (column_name 'amazonChoice'),
        "lowStock" boolean OPTIONS (column_name 'lowStock'),
        "sellParty" text OPTIONS (column_name 'sellParty'),
        "amazonSellParty" text OPTIONS (column_name 'amazonSellParty'),
        "amazonSell" text OPTIONS (column_name 'amazonSell'),
        MARKETPLACE boolean OPTIONS (column_name 'marketplace'),
        "marketplaceData" JSON OPTIONS (column_name 'marketplaceData'),
        "priceMatchDescription" text OPTIONS (column_name 'priceMatchDescription'),
        "priceMatch" boolean OPTIONS (column_name 'priceMatch'),
        "priceLock" boolean OPTIONS (column_name 'priceLock'),
        "isNpd" boolean OPTIONS (column_name 'isNpd'),
        SELL text OPTIONS (column_name 'sell'),
        "fulfilParty" text OPTIONS (column_name 'fulfilParty'),
        "amazonFulfilParty" text OPTIONS (column_name 'amazonFulfilParty'),
        STATUS text OPTIONS (column_name 'status'),
        SCREENSHOT text OPTIONS (column_name 'screenshot'),
        RANKING_DATA "productsData"[] OPTIONS (column_name 'ranking_data')
        )
    SERVER PRODDB_FDW
    OPTIONS (schema_name 'staging', table_name 'debug_tmp_product');

ALTER FOREIGN TABLE PRODDB_STAGING_FDW.DEBUG_TMP_PRODUCT
    OWNER TO POSTGRES;

